//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aff_Ins_LibraryDetails
    {
        public int IdAtu { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<int> Inst_ID { get; set; }
        public string Subject { get; set; }
        public string No_Of_Titles { get; set; }
        public string No_Of_Books { get; set; }
        public string No_Of_Relevant_Book { get; set; }
        public string No_Of_Reference_Books { get; set; }
        public string Other_Related { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Remove_Date { get; set; }
    }
}
