//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aff_ins_Application
    {
        public int IDAtu { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> Inst_ID { get; set; }
        public Nullable<int> Aff_Year { get; set; }
        public Nullable<bool> IS_submit { get; set; }
        public Nullable<bool> IS_verify_Dreft { get; set; }
        public Nullable<bool> Is_visit { get; set; }
        public Nullable<bool> Is_visit_assign { get; set; }
        public Nullable<System.DateTime> Visit_assign_date { get; set; }
        public Nullable<System.DateTime> visit_date { get; set; }
        public Nullable<bool> Is_Grant_Affiliation { get; set; }
        public Nullable<System.DateTime> insertion_date { get; set; }
        public Nullable<System.DateTime> modefied_date { get; set; }
        public Nullable<System.DateTime> Grant_date { get; set; }
        public Nullable<int> Securty_status { get; set; }
        public Nullable<System.DateTime> Affil_Notifection_Date { get; set; }
        public string Affil_Notifection_No { get; set; }
    }
}
