//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affi_Ins_StaffDetails
    {
        public int IdAtu { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> Inst_ID { get; set; }
        public string Emp_name { get; set; }
        public string Emp_Category { get; set; }
        public string Emp_Degree { get; set; }
        public string Emp_subject { get; set; }
        public string Emp_PassingYear { get; set; }
        public string Emp_Experience { get; set; }
        public string Emp_Deg_University { get; set; }
        public string Emp_Designation { get; set; }
        public string Emp_Nature_Of_appointment { get; set; }
        public string Emp_salary { get; set; }
        public Nullable<System.DateTime> Emp_Date_Appointment { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> remove_date { get; set; }
    }
}
