//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affi_ins_other_decplines
    {
        public int IdAtu { get; set; }
        public Nullable<int> ID { get; set; }
        public string Decpline_Name { get; set; }
        public Nullable<int> Decplin_Ins_ID { get; set; }
        public Nullable<int> No_OF_Seat { get; set; }
        public Nullable<System.DateTime> Insertion_Date { get; set; }
        public Nullable<System.DateTime> Updation_Date { get; set; }
        public Nullable<System.DateTime> Remove_date { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
