//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affi_Ins_Apply_Programs
    {
        public int IdAtu { get; set; }
        public Nullable<int> id { get; set; }
        public Nullable<int> Inst_ID { get; set; }
        public Nullable<int> App_ID { get; set; }
        public Nullable<int> Year { get; set; }
        public string Program_Apply_Category { get; set; }
        public Nullable<int> Program_ID { get; set; }
        public Nullable<int> No_Of_Seat { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> insertion_Date { get; set; }
        public Nullable<System.DateTime> Last_Modified_Date { get; set; }
        public Nullable<System.DateTime> Remove_Date { get; set; }
        public Nullable<bool> Is_Affi_Grant { get; set; }
        public Nullable<int> Recommand_seats { get; set; }
        public Nullable<int> Grant_seats { get; set; }
        public Nullable<int> consumed_seats { get; set; }
        public Nullable<int> Dep_Secuerty { get; set; }
    }
}
