//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affi_ins_Non_Recuring_R_and_E
    {
        public int idAut { get; set; }
        public int ID { get; set; }
        public int Inst_Id { get; set; }
        public string Opening_Balance_R { get; set; }
        public string College_FundsFee_R { get; set; }
        public string Gov_grant_R { get; set; }
        public string Other_R { get; set; }
        public string Total_R { get; set; }
        public string Bl_Construction_E { get; set; }
        public string Bl_Repair_E { get; set; }
        public string Bl_Other_E { get; set; }
        public string Fr_Purchase_E { get; set; }
        public string Fr_Repair_E { get; set; }
        public string Fr_Other_E { get; set; }
        public string Eq_Purchase_E { get; set; }
        public string Eq_Repair { get; set; }
        public string Eq_Other_E { get; set; }
        public string Libry_E { get; set; }
        public string Other_E { get; set; }
        public string Total_E { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> remove_date { get; set; }
        public Nullable<System.DateTime> First_Insertion_Date { get; set; }
        public Nullable<System.DateTime> Last_Modified_date { get; set; }
    }
}
