//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class affi_program_security_deposits
    {
        public int ID { get; set; }
        public Nullable<int> program_id { get; set; }
        public string exam_type { get; set; }
        public Nullable<int> program_security { get; set; }
        public Nullable<int> student_share { get; set; }
    }
}
