//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class affi_ins_disaffiliation
    {
        public int ID { get; set; }
        public Nullable<int> inst_id { get; set; }
        public Nullable<int> application_id { get; set; }
        public Nullable<System.DateTime> D_aaffiliation_date { get; set; }
        public string Remarks { get; set; }
    }
}
