//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affi_ins_Recipts
    {
        public int IdAto { get; set; }
        public int ID { get; set; }
        public int inst_id { get; set; }
        public string Recipt_Desc { get; set; }
        public string Amount { get; set; }
        public Nullable<bool> Is_Recurring_Recipts { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> insertion_Date { get; set; }
        public Nullable<System.DateTime> Last_modified_Date { get; set; }
        public Nullable<System.DateTime> remove_Date { get; set; }
    }
}
