//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affil_Ins_Bulid_Info
    {
        public int IdAtu { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> Int_ID { get; set; }
        public string Int_Buld_Name { get; set; }
        public Nullable<double> Int_Buld_Cov_Area { get; set; }
        public Nullable<double> Int_Buld_Uncov_Area { get; set; }
        public byte[] Inst_buld_Doc { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> InactiveDate { get; set; }
        public string imageName { get; set; }
    }
}
