//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affi_Ins_RoomDetails
    {
        public int IdAtu { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> Int_Bild_ID { get; set; }
        public string RoomType { get; set; }
        public Nullable<double> Rom_Lenght { get; set; }
        public Nullable<double> Rom_Width { get; set; }
        public Nullable<int> qty { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Remove_date { get; set; }
        public Nullable<int> Inst_ID { get; set; }
    }
}
