//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affi_Admin_User
    {
        public int IdAtu { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<int> PersonID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public Nullable<bool> status { get; set; }
        public string LoginPurpose { get; set; }
    }
}
