//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affi_ins_Draft_Detail
    {
        public int IDato { get; set; }
        public int ID { get; set; }
        public int inst_id { get; set; }
        public Nullable<int> App_ID { get; set; }
        public string Draft_amount { get; set; }
        public Nullable<System.DateTime> Deposit_Date { get; set; }
        public string Bank_Name { get; set; }
        public string Bank_Address { get; set; }
        public string Bank_branch_code { get; set; }
        public byte[] Draft_scan { get; set; }
        public Nullable<System.DateTime> insertion_date { get; set; }
        public Nullable<System.DateTime> last_Modified_date { get; set; }
        public Nullable<System.DateTime> remove_Date { get; set; }
        public Nullable<int> Status { get; set; }
        public string ScanName { get; set; }
    }
}
