//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affi_Int_Owner_Info
    {
        public int IdAtu { get; set; }
        public int Int_ID { get; set; }
        public int ID { get; set; }
        public string Int_Owner_Name { get; set; }
        public string Owner_Cnic { get; set; }
        public string Owner_Contact { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Remove_Date { get; set; }
    }
}
