//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affi_Com_Members
    {
        public int idato { get; set; }
        public Nullable<int> ID { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string As_Com_Designation { get; set; }
        public string Department { get; set; }
        public string CNIC { get; set; }
        public string Cell { get; set; }
        public Nullable<int> for_the_year { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Member_ID { get; set; }
        public Nullable<System.DateTime> Insertion_Date { get; set; }
        public Nullable<System.DateTime> Inactive_Date { get; set; }
        public Nullable<int> com_designation_ID { get; set; }
    }
}
