//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affi_Admin_PerForma_Details
    {
        public int IDAtu { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Aff_ID { get; set; }
        public Nullable<int> Inst_ID { get; set; }
        public Nullable<int> Performa_ID { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
