//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affi_ins_recipt_t_amount_summary
    {
        public int idatu { get; set; }
        public Nullable<int> inst_id { get; set; }
        public string Total_Amount { get; set; }
        public Nullable<bool> is_Recurring { get; set; }
    }
}
