//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affi_ins_Other_Decplines_Inst
    {
        public int IdAtu { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> Ins_ID { get; set; }
        public Nullable<int> BoardID { get; set; }
        public byte[] BoardScan { get; set; }
        public Nullable<int> ForYear { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
