//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affil_Ins_Info
    {
        public int IdAtu { get; set; }
        public Nullable<int> ID { get; set; }
        public string Ins_Name { get; set; }
        public string Ins_PostAddres { get; set; }
        public string Ins_ContactPTCL { get; set; }
        public string Ins_OfficMobile { get; set; }
        public string Ins_PrinciPal_Name { get; set; }
        public string PrinciPal_Contsact { get; set; }
        public Nullable<bool> Ins_IsGov { get; set; }
        public string Ins_Affi_Type { get; set; }
        public string Ins_Email { get; set; }
        public Nullable<int> Cuntry { get; set; }
        public Nullable<int> Province_id { get; set; }
        public Nullable<int> Districts_id { get; set; }
        public Nullable<int> Tehsils_ID { get; set; }
        public Nullable<int> Inst_code { get; set; }
    }
}
