//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affi_ins_Year
    {
        public int IDAtu { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> Aff_Year { get; set; }
        public Nullable<System.DateTime> Start_date { get; set; }
        public Nullable<System.DateTime> Last_Date { get; set; }
        public Nullable<System.DateTime> S_start_date { get; set; }
        public Nullable<System.DateTime> S_last_date { get; set; }
        public Nullable<System.DateTime> T_start_date { get; set; }
        public Nullable<System.DateTime> T_last_date { get; set; }
        public Nullable<bool> Isclosed { get; set; }
    }
}
