//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affi_ins_expenditure_t_amount_summary
    {
        public int idAtu { get; set; }
        public int inst_id { get; set; }
        public string total_amount { get; set; }
        public Nullable<bool> is_recurring { get; set; }
    }
}
