//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affi_ins_program_security_deposit
    {
        public int id_auto { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> inst_ID { get; set; }
        public Nullable<int> program_ID { get; set; }
        public Nullable<int> Deposit_amount { get; set; }
        public Nullable<System.DateTime> Deposit_date { get; set; }
        public Nullable<System.DateTime> Return_Date { get; set; }
        public Nullable<int> Refund_Status { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Dreft_ID { get; set; }
        public Nullable<bool> is_verify { get; set; }
        public Nullable<int> Apply_ID { get; set; }
    }
}
