//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eligibility_Check
    {
        public int ID { get; set; }
        public Nullable<int> year_ID { get; set; }
        public Nullable<int> Dep_ID { get; set; }
        public Nullable<int> Prog_catg { get; set; }
        public Nullable<int> Program_Type { get; set; }
        public Nullable<int> Program_ID { get; set; }
        public string Req_program_string { get; set; }
        public Nullable<bool> EqualEdu { get; set; }
        public Nullable<int> Req_marks { get; set; }
        public string Req_subject1_ID { get; set; }
        public Nullable<int> Req_subject1_Tmarks { get; set; }
        public Nullable<int> Req_subject1_Omarks { get; set; }
        public string Req_subject2_ID { get; set; }
        public Nullable<int> Req_subject2_Tmarks { get; set; }
        public Nullable<int> Req_subject2_Omarks { get; set; }
        public string Req_subject3_ID { get; set; }
        public Nullable<int> Req_subject3_Tmarks { get; set; }
        public Nullable<int> Req_subject3_Omarks { get; set; }
    }
}
