//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee_Slip
    {
        public int ID { get; set; }
        public Nullable<int> st_id { get; set; }
        public Nullable<int> rt_id { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public Nullable<int> app_id { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public string Peried_For { get; set; }
        public string Slip_Status { get; set; }
        public Nullable<System.DateTime> UpTo_Date { get; set; }
        public Nullable<int> Prog_Cat_ID { get; set; }
        public Nullable<System.DateTime> Recive_Date { get; set; }
        public string Branch_Name { get; set; }
        public byte[] Scan { get; set; }
        public string Branch_Code { get; set; }
        public Nullable<int> Admin_verify { get; set; }
    }
}
