//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee_Initial_Catagery
    {
        public int ID { get; set; }
        public Nullable<int> Department_ID { get; set; }
        public Nullable<int> Fee_Head { get; set; }
        public string Fee_Catag_Name { get; set; }
    }
}
