//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee_Initial_Details
    {
        public int ID { get; set; }
        public Nullable<int> Depertment_ID { get; set; }
        public Nullable<int> Fee_Head_ID { get; set; }
        public Nullable<int> Fee_catag_ID { get; set; }
        public Nullable<int> Program_ID { get; set; }
        public Nullable<int> Fee_Amount { get; set; }
        public Nullable<int> Year_ID { get; set; }
        public Nullable<int> Program_Catg { get; set; }
        public Nullable<int> Fee_def_ID { get; set; }
    }
}
