//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intermediate_Programs
    {
        public int ID { get; set; }
        public string Inter_Program { get; set; }
        public Nullable<int> Level_ID { get; set; }
    }
}
