//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogIn_User_type
    {
        public int IdAtu { get; set; }
        public Nullable<int> Id { get; set; }
        public string User_Type { get; set; }
        public Nullable<int> Institut_Typ { get; set; }
    }
}
