//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OldStudentRegistrationNo
    {
        public int ID { get; set; }
        public string Cnic { get; set; }
        public string StudentRegNo { get; set; }
        public Nullable<int> IS_Student { get; set; }
    }
}
