//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prog_Eligibility_Check_Info
    {
        public int ID { get; set; }
        public string Req_program_string { get; set; }
        public string Programs { get; set; }
        public string Subjects1 { get; set; }
        public string Subjects2 { get; set; }
    }
}
