//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg_return_status
    {
        public int ID { get; set; }
        public Nullable<int> app_id { get; set; }
        public Nullable<int> program_ID { get; set; }
        public Nullable<int> inst_id { get; set; }
        public Nullable<System.DateTime> return_send_date { get; set; }
        public Nullable<int> no_stu_Accept { get; set; }
        public Nullable<int> no_stu_Reject { get; set; }
        public Nullable<int> no_stu_Send { get; set; }
        public Nullable<int> no_stu_alreadyRegistered { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> year_id { get; set; }
        public Nullable<System.DateTime> Reg_Verfy_date { get; set; }
    }
}
