//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg_Admin_Fee_Verify
    {
        public int ID { get; set; }
        public Nullable<int> Fee_slip { get; set; }
        public Nullable<int> Ret_ID { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> Chlan_Upload_Date { get; set; }
        public Nullable<bool> Verify { get; set; }
        public Nullable<System.DateTime> Very_date { get; set; }
    }
}
