//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stu_Admin_Reg_Status_details
    {
        public int ID { get; set; }
        public Nullable<int> St_ID { get; set; }
        public Nullable<int> St_Ap { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Reg_Date { get; set; }
        public Nullable<int> Reg { get; set; }
    }
}
