//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stu_bachelors_info
    {
        public int b_id { get; set; }
        public int st_id { get; set; }
        public string degree_type { get; set; }
        public string degree_name { get; set; }
        public string university_name { get; set; }
        public Nullable<int> passing_year { get; set; }
        public string roll_number { get; set; }
        public Nullable<int> obtained_marks { get; set; }
        public Nullable<int> total_marks { get; set; }
        public string division { get; set; }
        public Nullable<double> percentage { get; set; }
        public string nature_of_exam { get; set; }
        public string exam_type { get; set; }
        public byte[] degree_scan { get; set; }
        public string image_name { get; set; }
        public string B_major_subject1_Name { get; set; }
        public Nullable<int> B_major_subject1_Tmarks { get; set; }
        public Nullable<int> B_major_subject1_Omarks { get; set; }
        public string B_major_subject2_Name { get; set; }
        public Nullable<int> B_major_subject2_Tmarks { get; set; }
        public Nullable<int> B_major_subject2_Omarks { get; set; }
        public string B_major_subject3_Name { get; set; }
        public Nullable<int> B_major_subject3_Tmarks { get; set; }
        public Nullable<int> B_major_subject3_Omarks { get; set; }
    }
}
