//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stu_affiliated_apply_program_info
    {
        public int ID { get; set; }
        public int st_id { get; set; }
        public int inst_id { get; set; }
        public int app_id { get; set; }
        public int program_id { get; set; }
        public Nullable<System.DateTime> Admission_date { get; set; }
        public string rol_number { get; set; }
        public string session { get; set; }
        public Nullable<int> status { get; set; }
    }
}
