//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stu_inter_info
    {
        public int I_ID { get; set; }
        public int st_id { get; set; }
        public string i_degree_name { get; set; }
        public string i__major_subject1 { get; set; }
        public Nullable<int> i__major_subject1_t_numbers { get; set; }
        public Nullable<int> i__major_subject1_numbers { get; set; }
        public string i__major_subject2 { get; set; }
        public Nullable<int> i__major_subject2_t_numbers { get; set; }
        public Nullable<int> i__major_subject2_numbers { get; set; }
        public string i__major_subject3 { get; set; }
        public Nullable<int> i__major_subject3_t_numbers { get; set; }
        public Nullable<int> i__major_subject3_numbers { get; set; }
        public Nullable<int> i_board_id { get; set; }
        public Nullable<int> i_passing_year { get; set; }
        public string i_examination_type { get; set; }
        public string i_rollnumber { get; set; }
        public Nullable<int> i_total_marks { get; set; }
        public Nullable<int> i_obtained_marks { get; set; }
        public string i_division { get; set; }
        public Nullable<double> i_percentage { get; set; }
        public byte[] i_result_scan { get; set; }
        public string image_name { get; set; }
    }
}
