//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stu_applied_reg_f_affi_clg
    {
        public int id { get; set; }
        public int inst_id { get; set; }
        public Nullable<int> st_id { get; set; }
        public Nullable<int> app_id { get; set; }
        public Nullable<int> program_id { get; set; }
        public Nullable<int> year_id { get; set; }
        public Nullable<System.DateTime> admission_date { get; set; }
        public Nullable<System.DateTime> send_return_date { get; set; }
        public string roll_number { get; set; }
        public Nullable<int> is_active { get; set; }
        public Nullable<int> is_in_reurn { get; set; }
        public string Prog_session { get; set; }
        public Nullable<int> St_Enroll_status { get; set; }
        public Nullable<int> IS_Drop_Return { get; set; }
        public Nullable<int> institute_category_Id { get; set; }
        public Nullable<int> Is_Eligible { get; set; }
        public Nullable<int> Is_Registion_UOS { get; set; }
        public string Prog_Category { get; set; }
        public Nullable<int> Is_Student { get; set; }
        public Nullable<int> Class_Section { get; set; }
    }
}
