//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stu_basic_info
    {
        public int st_id { get; set; }
        public string reg_number { get; set; }
        public string st_name { get; set; }
        public string Father_name { get; set; }
        public Nullable<System.DateTime> st_dob { get; set; }
        public string st_birth_place { get; set; }
        public string st_contact { get; set; }
        public string st_bloodgroup { get; set; }
        public string st_email { get; set; }
        public string st_gender { get; set; }
        public string st_martial_status { get; set; }
        public string st_religion { get; set; }
        public string st_cinc { get; set; }
        public string st_nationality { get; set; }
        public Nullable<int> st_pr_country_id { get; set; }
        public Nullable<int> st_pr_provience_id { get; set; }
        public Nullable<int> st_pr_dist_id { get; set; }
        public Nullable<int> st_pr_tehsil_id { get; set; }
        public string st_pr_address { get; set; }
        public Nullable<int> st_counter_id { get; set; }
        public Nullable<int> st_provience_id { get; set; }
        public Nullable<int> st_dist_id { get; set; }
        public Nullable<int> st_tehsil_id { get; set; }
        public string st_address { get; set; }
        public string st_gr_name { get; set; }
        public string st_gr_cnic { get; set; }
        public string st_gr_cell { get; set; }
        public string st_relation_id { get; set; }
        public string st_gr_eaducation { get; set; }
        public string st_gr_occupation { get; set; }
        public string st_gr_job_sector { get; set; }
        public Nullable<int> st_gr_anual_income { get; set; }
        public byte[] st_image { get; set; }
        public string image_name { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> st_Current_Status { get; set; }
    }
}
