//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uos_All_Programs_Cat
    {
        public int ID { get; set; }
        public string Program_Desc { get; set; }
        public Nullable<int> Order_ID { get; set; }
        public Nullable<int> Uni_Program { get; set; }
    }
}
