//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Login_Detail
    {
        public int IdAtu { get; set; }
        public Nullable<int> ID { get; set; }
        public string EmailID { get; set; }
        public string Pass { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public Nullable<int> Institut_ID { get; set; }
        public Nullable<bool> isdisabled { get; set; }
    }
}
