//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Apply_Roll
    {
        public int IdAtu { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> RollID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
