//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Roll_Defination
    {
        public int IdAtu { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> User_Type { get; set; }
        public string User_Roll { get; set; }
        public Nullable<bool> IsActiv { get; set; }
    }
}
