//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Aff_Student_reg_FeeSlip_info
    {
        public string Slip_ID { get; set; }
        public Nullable<System.DateTime> recive_date { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> st_id { get; set; }
        public int Std_Slip_ID { get; set; }
        public Nullable<int> rt_id { get; set; }
        public Nullable<int> programID { get; set; }
        public Nullable<int> std_application_ID { get; set; }
    }
}
